from langchain_core.embeddings import Embeddings as EmbeddingsModel
from unlp_2026_submission.embeddings.google_embeddings_model import GoogleEmbeddingsModel
from unlp_2026_submission.embeddings.open_ai_embeddings_model import OpenAIEmbeddingsModel
